# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RDistParNelderMead <- function(par, fn, fn_arg = NULL, max_iterations = -1L) {
    .Call(`_RDistParNelderMead_RDistParNelderMead`, par, fn, fn_arg, max_iterations)
}

RMPI_Finalize <- function() {
    invisible(.Call(`_RDistParNelderMead_RMPI_Finalize`))
}

